### ISSUE TITLE
CPU Sampling spontaneously stops updating

### ISSUE THREAD

**Issue by swpalmer** [oracle/visualvm#480] opened 2023-01-16 15:51 UTC
**Describe the bug**
When I activate CPU sampling it runs for a while, sometimes 10 seconds, sometimes 10 minutes, and then the updates simply stop.
VisualVM claims that CPU sampling is active, but no additional data appears to be collected.  Closing the tab for the application and reopening it allows CPU sampling to be started again.
If you attempt to stop and start CPU sampling without closing and reopening the application tab, the log file shows:
```
SEVERE [org.openide.util.RequestProcessor]: Error in RequestProcessor org.graalvm.visualvm.sampler.SamplerImpl$5$1$1
java.lang.IllegalStateException: Timer already cancelled.
	at java.base/java.util.Timer.sched(Timer.java:409)
	at java.base/java.util.Timer.scheduleAtFixedRate(Timer.java:340)
	at org.graalvm.visualvm.sampler.cpu.CPUSamplerSupport.startSampling(CPUSamplerSupport.java:180)
	at org.graalvm.visualvm.sampler.SamplerImpl$5$1$1.run(SamplerImpl.java:438)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```

**To Reproduce**
1. Start monitoring an application
2. Click on 'Sampler'
3. Click on 'CPU' - Status changes from 'sampling inactive' to 'CPU sampling in progress'
4. Watch the table update.  Sorted by 'Total time' you should see the ms values updating approximately once per second.  After some time these updates simply stop and the table will remain static forever after that.  The status is still reported as 'CPU sampling in progress'

**Expected behavior**
The sampling should continue until it is manually stopped.

**VisualVM log**
[VisualVM_logfile.zip](https://github.com/oracle/visualvm/files/10427255/VisualVM_logfile.zip)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.14393]
 - JDK version
   Java; VM; Vendor        = 19.0.1; OpenJDK 64-Bit Server VM 19.0.1+10; Azul Systems, Inc.
   Runtime                 = OpenJDK Runtime Environment 19.0.1+10
 - Version 2.1.5

**Additional context**
Monitored application is running on :
openjdk 17.0.5 2022-10-18 LTS
OpenJDK Runtime Environment Zulu17.38+21-CA (build 17.0.5+8-LTS)
OpenJDK 64-Bit Server VM Zulu17.38+21-CA (build 17.0.5+8-LTS, mixed mode)

**Comment by thurka** [comment] 2023-01-23 11:44
I am not able to reproduce it. Are you able to reproduce it with some public java app like JDK demos? It would be great if you can put together reproducible test case. Thanks.

**Comment by thurka** [comment] 2023-11-01 10:20
Closing util more info is available.

**Closed by thurka** 2023-11-01 10:20 UTC
Labels: bug
