### ISSUE TITLE
StackOverflowError at Startup Profiler

### ISSUE THREAD

**Issue by stsypanov** [oracle/visualvm#51] opened 2018-01-10 20:02 UTC
I run VisualVM with installed Startup Profiler under Windows 7.
When I try to launch Startup Profiler just like mentioned [here](https://visualvm.github.io/startupprofiler.html) I get errors mentioned in the log.

[messages.log](https://github.com/oracle/visualvm/files/1620270/messages.log)

--------------------------------------------------------------
Version: 
1.4 (Build 171211); platform 20171211-unknown-revn

System: 
Windows 7 (6.1) Service Pack 1, amd64 64bit

Java: 
1.8.0_144; Java HotSpot(TM) 64-Bit Server VM (25.144-b01, mixed mode)

Vendor: 
Oracle Corporation, http://java.oracle.com/

Environment: 
Cp1251; ru_RU (visualvm)

Clusters: 
G:\visualvm_14\platform
G:\visualvm_14\visualvm
G:\visualvm_14\profiler

**Comment by jisedlac** [comment] 2018-01-11 12:16
Thanks for the bugreport! The bug is caused by incorrect UI implementation for Windows Classic LaF on our side.

As a workaround until fixed, either switch your Windows 7 to the default appearance (Aero) or start VisualVM with a different LaF: visualvm.exe --laf Metal .

**Comment by jisedlac** [comment] 2018-01-11 12:17
This bug also affects the Memory Settings pane in Profiler tab when running using the Windows Classic LaF.

**Comment by jisedlac** [comment] 2018-01-12 12:33
Fixed in master.

**Closed by jisedlac** 2018-01-12 12:33 UTC
Labels: bug
