### ISSUE TITLE
Sampler ignores settings

### ISSUE THREAD

**Issue by aldaris** [oracle/visualvm#71] opened 2018-03-17 13:02 UTC
When trying to use the 1.4 version of VisualVM it appears that the Sampler ignores the package settings and just ends up profiling every package/class. Switching back to 1.3.9 seems to resolve this.

**Comment by jisedlac** [comment] 2018-03-19 10:12
VisualVM 1.3.9 shows Hot Spots (table) by default, VisualVM 1.4 shows Call Trees (treetable) by default. Each of these views present the data in a different way.

If you take a snapshot using the 1.4 Sampler and switch to the Hot Spots table, you should see the same results as in 1.3.9.

**Comment by aldaris** [comment] 2018-03-19 10:26
I've never taken a snapshot before simply because there wasn't a need. In 1.4 it took some effort to find the hotspot view, but then it included all classes. Just for fun I've tried taking a snapshot and the hotspot view for the snapshot is still listing all the classes.

My settings were literally:

```
com.sun.identity.**
com.iplanet.**
org.forgerock.**
```

Is the setting in the wrong format, or could it be that these settings are parsed incorrectly?

**Comment by thurka** [comment] 2020-09-11 19:31
This is duplicate of GH-85.

**Closed by thurka** 2020-09-11 19:31 UTC
