### ISSUE TITLE
Profiler Agent Error: Exception when trying to send response or command to client: UTFDataFormatException

### ISSUE THREAD

**Issue by nestorjb** [oracle/visualvm#81] opened 2018-04-26 03:15 UTC
Hi

I'm using the latest VisualVM 1.4.1 release on OpenJDK 1.8.0_131. When I try to run the Memory Profiling tool I get on the console of the Java process:

Profiler Agent: JNI OnLoad Initializing...
Profiler Agent: JNI OnLoad Initialized successfully
Profiler Agent: Waiting for connection on port 5140 (Protocol version: 18)
Profiler Agent: Established connection with the tool
Profiler Agent Error: Exception when trying to send response or command to client:
java.io.UTFDataFormatException
java.io.UTFDataFormatException
	at java.io.ObjectOutputStream$BlockDataOutputStream.writeUTF(ObjectOutputStream.java:2164)
	at java.io.ObjectOutputStream$BlockDataOutputStream.writeUTF(ObjectOutputStream.java:2007)
	at java.io.ObjectOutputStream.writeUTF(ObjectOutputStream.java:869)
	at org.netbeans.lib.profiler.wireprotocol.VMPropertiesResponse.writeObject(VMPropertiesResponse.java:203)
	at org.netbeans.lib.profiler.wireprotocol.WireIO.sendComplexResponse(WireIO.java:336)
	at org.netbeans.lib.profiler.server.ProfilerServer.sendComplexResponseToClient(ProfilerServer.java:724)
	at org.netbeans.lib.profiler.server.ProfilerServer.handleClientCommand(ProfilerServer.java:1614)
	at org.netbeans.lib.profiler.server.ProfilerServer.listenToClient(ProfilerServer.java:1777)
	at org.netbeans.lib.profiler.server.ProfilerServer.run(ProfilerServer.java:700)
Profiler Agent: Connection with agent closed
Profiler Agent: Connection with agent closed

Any ideas?

**Comment by thurka** [comment] 2018-04-27 08:54
It looks like there are some strange characters on the classpath of your profiled application. Can you please create application snapshot from your application and attach it to this issue? The classpath should be visible in system properties tab.

**Comment by thurka** [comment] 2018-11-02 07:49
It looks like the problem is caused by extremely long classpath of your profiler application (system property `java.class.path`). Please take an Application Snapshot of the application you want to profile and attach it to this issue. This way we can verify this hypothesis.

**Comment by mirkoebert** [comment] 2018-11-02 08:01
My problem is, thats not my application and I can't put a snapshot here, but I try a different app and hope to see the same problem.

**Comment by thurka** [comment] 2018-11-13 09:35
> My problem is, thats not my application and I can't put a snapshot here, but I try a different app and hope to see the same problem.

Any update? 
BTW: I am not sure why the fact that it is not your application, prevents you to add an Application Snapshot to this issue.

**Comment by flozano** [comment] 2020-01-08 10:55
I'm getting the same

**Comment by thurka** [comment] 2020-12-22 13:37
Hopefully fixed in master.

**Closed by thurka** 2020-12-22 13:37 UTC
Labels: bug
