### ISSUE TITLE
Polyglot Sampler not showing up

### ISSUE THREAD

**Issue by fniephaus** [oracle/visualvm#218] opened 2020-07-17 08:44 UTC
**Describe the bug**
According to [this](https://github.com/oracle/visualvm/commit/980ee433836651e6184f6e2cd7ddb596bb28009c), a Polyglot Sampler tab is supposed to be visible in VisualVM 2.0.3. It seems that it's still not showing up correctly.

**To Reproduce**
1. Run `polyglot --jvm --shell` with  a GraalVM 20.1
2. Open VisualVM on the process

**Expected behavior**
Polyglot Sampler tab shows up.

**Screenshots**
The [commit](https://github.com/oracle/visualvm/commit/980ee433836651e6184f6e2cd7ddb596bb28009c) shows that VisualVM checks whether `jvm.getVmName().contains("GraalVM")`. `java.vm.name` properties of GraalVM 20.1.0 releases, however, do not contain "GraalVM":

#### GraalVM CE 20.1
![image](https://user-images.githubusercontent.com/2368856/87766713-e205f400-c819-11ea-9e97-e544d48fa03f.png)
#### GraalVM EE 20.1
![image](https://user-images.githubusercontent.com/2368856/87766694-db777c80-c819-11ea-8374-ec4cc4268675.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - JDK version GraalVM CE 20.1.0

**Comment by thurka** [comment] 2020-07-17 09:13
I need more info, since I am not able to reproduce it. See attached screenshot.
<img width="1052" alt="polygnot" src="https://user-images.githubusercontent.com/22048069/87769858-7bcfa000-c81e-11ea-8cea-895480a248e1.png">

**Comment by fniephaus** [comment] 2020-07-17 09:59
I'm running on JDK11, apparently the `vm.name` does not contain it there for some reason. I'll file another bug against oracle/graal...Nonetheless, I'm not sure this is the best way to check for GraalVM.

**Comment by fniephaus** [comment] 2020-07-17 10:23
Apart from this bringing up a bug in GraalVM, I don't think VisualVM's check is correct. You can run on an OpenJDK/LabsJDK with Graal/Truffle, and that will not have "GraalVM" in the `vm.name`. Maybe a check whether there is a property starting with `org.graalvm` is better. It feels like there should be one official and correct way to do this though.

**Comment by fniephaus** [comment] 2020-08-11 15:16
[According to @dougxc](https://github.com/oracle/graal/issues/2689#issuecomment-672007385):
> The property to check in JDK 11 is `java.vendor.version.`

**Comment by thurka** [comment] 2020-11-02 10:27
Fixed in master.

**Closed by thurka** 2020-11-02 10:27 UTC
Labels: bug
