### ISSUE TITLE
NPE loading a heap dump in VisualVM

### ISSUE THREAD

**Issue by dfuch** [oracle/visualvm#546] opened 2024-01-12 10:55 UTC
**Describe the bug**

Using File -> Load to load a heap dump (.hprof) a new heapdump tab is created, but the tab stays blank.
In VisualVM log file I see:

SEVERE [org.openide.util.RequestProcessor]: Error in RequestProcessor org.graalvm.visualvm.heapviewer.ui.HeapViewerComponent$1
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because "daemon" is null
	at org.graalvm.visualvm.heapviewer.java.impl.JavaThreadsProvider.getThreadName(JavaThreadsProvider.java:89)
	at org.graalvm.visualvm.heapviewer.java.impl.JavaThreadsSummary.<init>(JavaThreadsSummary.java:98)
	at org.graalvm.visualvm.heapviewer.java.impl.JavaThreadsSummary.<init>(JavaThreadsSummary.java:79)
	at org.graalvm.visualvm.heapviewer.java.impl.JavaThreadsSummary$Provider.createSummary(JavaThreadsSummary.java:297)
	at org.graalvm.visualvm.heapviewer.ui.SummaryView.<init>(SummaryView.java:76)
	at org.graalvm.visualvm.heapviewer.java.impl.JavaSummaryView.<init>(JavaSummaryView.java:56)
	at org.graalvm.visualvm.heapviewer.java.impl.JavaSummaryProvider.getFeature(JavaSummaryProvider.java:43)
	at org.graalvm.visualvm.heapviewer.ui.HeapViewerComponent.initImpl(HeapViewerComponent.java:142)
	at org.graalvm.visualvm.heapviewer.ui.HeapViewerComponent.access$000(HeapViewerComponent.java:76)
	at org.graalvm.visualvm.heapviewer.ui.HeapViewerComponent$1.run(HeapViewerComponent.java:95)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)

**Desktop (please complete the following information):**
 - OS: macOS x64
 - JDK version: JDK 21.0.1
 - Version: VisualVM 2.1.7 (but apparently also happens with 2.1.2) 

**Additional context**
The heap dump was produced with a mainline build of JDK 22 (under development)

**Comment by thurka** [comment] 2024-01-12 20:08
This looks to me like duplicate of GH-539. Do you use virtual threads?

**Closed** 2024-01-15 12:05 UTC
Labels: bug

**Comment by dfuch** [comment] 2024-01-15 15:17
Hi Tomas, yes - there were virtual threads in use. Thanks for the pointer to GH-539!
