### ISSUE TITLE
VisualVM default gtk plaf not working on a default Ubuntu install

### ISSUE THREAD

**Issue by JeromeA** [oracle/visualvm#364] opened 2021-11-19 12:15 UTC
**Describe the bug**
When running VisualVM on a default Ubuntu install, the UI seems to work, but any attempt to use the sample or the profiler silently fails.

**To Reproduce**
1. Install VisualVM on a minimal Ubuntu desktop configuration.
2. Start VisualVM, connect to a running app, and start the profiler.
3. Nothing happens in the UI, an exception is raised in the logs.

**VisualVM log**
[messages.log](https://github.com/oracle/visualvm/files/7570116/messages.log)

**Version**
 - OS: Ubuntu 21.04
 - System: Linux (5.11.0-38-generic) , amd64 64bit
 - JDK: OpenJDK 64-Bit Server VM (build 17+35-Ubuntu-121.04)
 - VisualVM: 2.1.1 (Build 210920); platform 20210621-2172674416

**Workaround**
`visualvm --laf Metal` works.

**Comment by thurka** [comment] 2021-11-19 14:51
Problem seems to be caused by changes in JDK. JDK 15 and older works fine, while JDK 16 and newer fails with above NPE. So another workaround is to run VisualVM on JDK 15 or older.

**Comment by thurka** [comment] 2021-11-22 10:04
This regression is caused by 
[JDK-8041705](https://bugs.openjdk.java.net/browse/JDK-8041705) - Bugs in DefaultTreeCellRenderer.updateUI()

**Comment by thurka** [comment] 2021-12-10 07:16
Fixed in master.

**Closed by thurka** 2021-12-10 07:16 UTC
Labels: bug
