### ISSUE TITLE
Java 10 - VisualVM 1.4.1 - Sampler -> CPU -> CPU Settings, doesn't filter.

### ISSUE THREAD

**Issue by bashscr1pt** [oracle/visualvm#85] opened 2018-05-09 17:31 UTC
when trying to sample the CPU, when you check the "settings" checkbox and look at the filters... it would appear not to be working.  sun.** and java.** or really anything doesn't get filtered out.

**Comment by ryan-richt** [comment] 2018-10-22 20:14
This also bug persists in VisualVM version 1.4.2, as well as against Java 11

**Comment by alaurenau** [comment] 2019-01-28 08:12
VisualVM version 1.4.2 is affected.
I am running on VisualVM Oracle JDK 1.8.0_192. Sampled application is on OpenJDK 1.8.0_141.

**Comment by vitaliy-sk** [comment] 2019-06-01 20:38
+1 

java version "11.0.3" 2019-04-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.3+12-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.3+12-LTS, mixed mode)

**Comment by rafaferry** [comment] 2019-09-11 16:14
+1 

openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.18.10.1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)

**Comment by zhou-hao** [comment] 2020-02-27 12:15
+1 
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.232-b09, mixed mode)

**Comment by rcastagno** [comment] 2020-03-10 15:04
Filter seems broken in 2.0 too.

**Comment by ryan-richt** [comment] 2020-03-26 18:48
Has anyone figured out a work-around to this? For us, this makes VisualVM CPU sampling completely unusable, but I feel like we must be doing something wrong / thinking about it wrong, since this issue has been open for so long, and others must clearly be using this issue-free in the mean time? thank you all!

**Comment by Jammy42** [comment] 2020-04-01 22:18
Does anybody know in what VisualVM version the filtering still works ?

**Comment by rcastagno** [comment] 2020-04-01 23:15
@Jammy42 1.3.9 works for me

**Comment by thurka** [comment] 2020-04-02 09:56
Can you please provide step-by-step to reproduce it? Ideally with some simple java app. Thanks.

**Comment by Jammy42** [comment] 2020-04-02 10:40
@thurka 1.3.9 vs 1.4.4 (or 2.0.1)
1.3.9 : go to "Settings" and adjust "CPU Setting" for ex. rm java.*, then start CPU sampling : all java.* classes are listed. Then change java.* to java.lang.* : then all java.* classes are listed except those from java.lang, 

1.4.4 : do the same as above. You will see that the above changes have no effect.

**Comment by thurka** [comment] 2020-04-06 13:35
Detailed steps to reproduce are still needed - 1.3.9 and 1.4.4 displays different data in CPU view. 1.3.9 shows hotspots, but 1.4.4 shows call-tree. It is not clear to me, what and how do you compare 1.3.9 and 1.4.4. If I take a CPU snapshot in 1.3.9 - (to be able to compare it with 1.4.4) I don't see anything wrong. 1.3.9 and 1.4.4 call-tree data looks the same. So can you compare CPU snapshot from 1.3.9 with CPU snapshot from 1.4.4 and see if there are some differences?

**Comment by Jammy42** [comment] 2020-04-06 17:42
I hope the attached PDF shows you what the issue is. If you need easy access to a vm (to profile) pls send me a pm.
[visualvm.pdf](https://github.com/oracle/visualvm/files/4439949/visualvm.pdf)

**Comment by thurka** [comment] 2020-04-09 08:37
Thanks, I see the issue. To make sure that I understand the issue correctly,  can you, please, compare CPU snapshot from 1.3.9 with CPU snapshot from 1.4.4? There should be no difference, both snapshots should have `java.lang` classes in hotspots.

**Comment by Jammy42** [comment] 2020-04-09 10:44
Snapshot / Hot Methods
1.3.9 : the filter is not applied
1.4.4 : the filter is not applied 

=> I think for the hot methods it should also be possible to filter. Just consider this : I set the filter and do the sampling - then I take a snapshot and I don't see the view of the sampling anymore.

The idea of the filter is that I can create my own "hot method" setup. Where as in snapshot it's just the regular mess of methods like in Java Flight Controller.

**Comment by thurka** [comment] 2020-04-09 11:11
> Snapshot / Hot Methods
> 1.3.9 : the filter is not applied
> 1.4.4 : the filter is not applied

OK, the important part is that the data are the same. 

> 
> => I think for the hot methods it should also be possible to filter. Just consider this : I set the filter and do the sampling - then I take a snapshot and I don't see the view of the sampling anymore.

Yes, this should to be fixed. Until this is fixed, you can filter the hot methods yourself. Just right-click in hot spots methods view and select "Filter" from context menu.

> 
> The idea of the filter is that I can create my own "hot method" setup. Where as in snapshot it's just the regular mess of methods like in Java Flight Controller.

The situation is much more complicated than just that the filter does not work. Definitely is not a mess.

**Comment by Jammy42** [comment] 2020-04-09 11:20
>> The situation is much more complicated than just that the filter does not work. Definitely is not a mess.

Sorry, I was referring to Java Mission Control, where you can't Filter.

**Comment by thurka** [comment] 2020-05-22 10:40
Hopefully fixed in master, the fix will be part of the next VisualVM release (after VisualVM 2.0.2).

**Closed by thurka** 2020-05-22 10:40 UTC
Labels: bug
