### ISSUE TITLE
NPE when trying to inspect Ruby heap

### ISSUE THREAD

**Issue by fniephaus** [oracle/visualvm#208] opened 2020-06-09 15:29 UTC
I tried to inspect the Ruby heap in VisualVM (2.0.2 bundled with GraalVM 20.1.0 CE on macOS Catalina), but this is all I get:
![image](https://user-images.githubusercontent.com/2368856/84167525-a471b680-aa76-11ea-93dc-d4a9d4aec222.png)

The Python and R heap viewer seem to work just fine.

Here's the error:
```
java.lang.NullPointerException
	at org.graalvm.visualvm.heapviewer.truffle.dynamicobject.DynamicObjectDetailsProvider.getInstanceId(DynamicObjectDetailsProvider.java:111)
	at org.graalvm.visualvm.heapviewer.truffle.dynamicobject.DynamicObjectDetailsProvider.getJSUdefined(DynamicObjectDetailsProvider.java:100)
	at org.graalvm.visualvm.heapviewer.truffle.dynamicobject.DynamicObjectDetailsProvider.getDetailsString(DynamicObjectDetailsProvider.java:59)
	at org.graalvm.visualvm.lib.profiler.heapwalk.details.api.DetailsSupport.getDetailsString(DetailsSupport.java:70)
	at org.graalvm.visualvm.lib.profiler.heapwalk.details.spi.DetailsUtils.getInstanceString(DetailsUtils.java:204)
	at org.graalvm.visualvm.lib.profiler.heapwalk.details.spi.DetailsUtils.getInstanceFieldString(DetailsUtils.java:200)
	at org.graalvm.visualvm.heapviewer.truffle.details.SourceDetailsProvider.getDetailsString(SourceDetailsProvider.java:91)
	at org.graalvm.visualvm.lib.profiler.heapwalk.details.api.DetailsSupport.getDetailsString(DetailsSupport.java:70)
	at org.graalvm.visualvm.lib.profiler.heapwalk.details.spi.DetailsUtils.getInstanceString(DetailsUtils.java:204)
	at org.graalvm.visualvm.heapviewer.truffle.dynamicobject.DynamicObject$Property.<init>(DynamicObject.java:428)
	at org.graalvm.visualvm.heapviewer.truffle.dynamicobject.DynamicObject$Property.<init>(DynamicObject.java:418)
	at org.graalvm.visualvm.heapviewer.truffle.dynamicobject.DynamicObject.initFields(DynamicObject.java:226)
	at org.graalvm.visualvm.heapviewer.truffle.dynamicobject.DynamicObject.getFieldValues(DynamicObject.java:123)
	at org.graalvm.visualvm.heapviewer.truffle.dynamicobject.DynamicObject.getFieldValue(DynamicObject.java:128)
	at org.graalvm.visualvm.heapviewer.truffle.lang.ruby.RubyDetailsProvider.getDetailsString(RubyDetailsProvider.java:146)
	at org.graalvm.visualvm.lib.profiler.heapwalk.details.api.DetailsSupport.getDetailsString(DetailsSupport.java:70)
	at org.graalvm.visualvm.heapviewer.truffle.dynamicobject.DynamicObjectDetailsProvider.getDetailsString(DynamicObjectDetailsProvider.java:75)
	at org.graalvm.visualvm.lib.profiler.heapwalk.details.api.DetailsSupport.getDetailsString(DetailsSupport.java:70)
	at org.graalvm.visualvm.heapviewer.truffle.dynamicobject.DynamicObject.computeType(DynamicObject.java:172)
	at org.graalvm.visualvm.heapviewer.truffle.dynamicobject.DynamicObject.getType(DynamicObject.java:160)
	at org.graalvm.visualvm.heapviewer.truffle.TruffleType$TypesComputer.getTypeName(TruffleType.java:179)
	at org.graalvm.visualvm.heapviewer.truffle.TruffleType$TypesComputer.addObject(TruffleType.java:157)
	at org.graalvm.visualvm.heapviewer.truffle.TruffleLanguageHeapFragment.computeStatistics(TruffleLanguageHeapFragment.java:165)
	at org.graalvm.visualvm.heapviewer.truffle.TruffleLanguageHeapFragment.checkInitialized(TruffleLanguageHeapFragment.java:123)
	at org.graalvm.visualvm.heapviewer.truffle.TruffleLanguageHeapFragment.getHeapSize(TruffleLanguageHeapFragment.java:78)
	at org.graalvm.visualvm.heapviewer.truffle.ui.TruffleSummaryView$OverviewSection.computeHeapData(TruffleSummaryView.java:248)
	at org.graalvm.visualvm.heapviewer.truffle.ui.TruffleSummaryView$OverviewSection.computeData(TruffleSummaryView.java:234)
	at org.graalvm.visualvm.heapviewer.truffle.ui.TruffleSummaryView$1$1.run(TruffleSummaryView.java:124)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)

```

**Comment by thurka** [comment] 2020-06-09 17:18
This is duplicate of GH-196.

**Closed by thurka** 2020-06-09 17:18 UTC
