### ISSUE TITLE
NPE in Ruby heap viewer

### ISSUE THREAD

**Issue by chrisseaton** [oracle/visualvm#196] opened 2020-05-11 23:57 UTC
**Describe the bug**
NPE when using the Ruby view of the heap.

**To Reproduce**
Connected to a TruffleRuby process. Take a heap dump. Try to view as Ruby.

**Expected behavior**
Being able to see the Ruby heap.

**VisualVM log**
```
java.lang.NullPointerException
	at org.graalvm.visualvm.heapviewer.truffle.dynamicobject.DynamicObjectDetailsProvider.getInstanceId(DynamicObjectDetailsProvider.java:111)
	at org.graalvm.visualvm.heapviewer.truffle.dynamicobject.DynamicObjectDetailsProvider.getJSUdefined(DynamicObjectDetailsProvider.java:100)
	at org.graalvm.visualvm.heapviewer.truffle.dynamicobject.DynamicObjectDetailsProvider.getDetailsString(DynamicObjectDetailsProvider.java:59)
	at org.graalvm.visualvm.lib.profiler.heapwalk.details.api.DetailsSupport.getDetailsString(DetailsSupport.java:70)
	at org.graalvm.visualvm.lib.profiler.heapwalk.details.spi.DetailsUtils.getInstanceString(DetailsUtils.java:204)
	at org.graalvm.visualvm.lib.profiler.heapwalk.details.spi.DetailsUtils.getInstanceFieldString(DetailsUtils.java:200)
	at org.graalvm.visualvm.heapviewer.truffle.details.SourceDetailsProvider.getDetailsString(SourceDetailsProvider.java:91)
	at org.graalvm.visualvm.lib.profiler.heapwalk.details.api.DetailsSupport.getDetailsString(DetailsSupport.java:70)
	at org.graalvm.visualvm.lib.profiler.heapwalk.details.spi.DetailsUtils.getInstanceString(DetailsUtils.java:204)
	at org.graalvm.visualvm.heapviewer.truffle.dynamicobject.DynamicObject$Property.<init>(DynamicObject.java:428)
	at org.graalvm.visualvm.heapviewer.truffle.dynamicobject.DynamicObject$Property.<init>(DynamicObject.java:418)
	at org.graalvm.visualvm.heapviewer.truffle.dynamicobject.DynamicObject.initFields(DynamicObject.java:226)
	at org.graalvm.visualvm.heapviewer.truffle.dynamicobject.DynamicObject.getFieldValues(DynamicObject.java:123)
	at org.graalvm.visualvm.heapviewer.truffle.dynamicobject.DynamicObject.getFieldValue(DynamicObject.java:128)
	at org.graalvm.visualvm.heapviewer.truffle.lang.ruby.RubyDetailsProvider.getDetailsString(RubyDetailsProvider.java:146)
	at org.graalvm.visualvm.lib.profiler.heapwalk.details.api.DetailsSupport.getDetailsString(DetailsSupport.java:70)
	at org.graalvm.visualvm.heapviewer.truffle.dynamicobject.DynamicObjectDetailsProvider.getDetailsString(DynamicObjectDetailsProvider.java:75)
	at org.graalvm.visualvm.lib.profiler.heapwalk.details.api.DetailsSupport.getDetailsString(DetailsSupport.java:70)
	at org.graalvm.visualvm.heapviewer.truffle.dynamicobject.DynamicObject.computeType(DynamicObject.java:172)
	at org.graalvm.visualvm.heapviewer.truffle.dynamicobject.DynamicObject.getType(DynamicObject.java:160)
	at org.graalvm.visualvm.heapviewer.truffle.TruffleType$TypesComputer.getTypeName(TruffleType.java:179)
	at org.graalvm.visualvm.heapviewer.truffle.TruffleType$TypesComputer.addObject(TruffleType.java:157)
	at org.graalvm.visualvm.heapviewer.truffle.TruffleLanguageHeapFragment.computeStatistics(TruffleLanguageHeapFragment.java:165)
	at org.graalvm.visualvm.heapviewer.truffle.TruffleLanguageHeapFragment.checkInitialized(TruffleLanguageHeapFragment.java:123)
	at org.graalvm.visualvm.heapviewer.truffle.TruffleLanguageHeapFragment.getHeapSize(TruffleLanguageHeapFragment.java:78)
	at org.graalvm.visualvm.heapviewer.truffle.ui.TruffleSummaryView$OverviewSection.computeHeapData(TruffleSummaryView.java:248)
	at org.graalvm.visualvm.heapviewer.truffle.ui.TruffleSummaryView$OverviewSection.computeData(TruffleSummaryView.java:234)
	at org.graalvm.visualvm.heapviewer.truffle.ui.TruffleSummaryView$1$1.run(TruffleSummaryView.java:124)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
Caused: org.openide.util.RequestProcessor$SlowItem: task failed due to
	at org.openide.util.RequestProcessor.post(RequestProcessor.java:395)
	at org.graalvm.visualvm.heapviewer.truffle.ui.TruffleSummaryView$1.uiCreated(TruffleSummaryView.java:120)
	at org.graalvm.visualvm.heapviewer.ui.SummaryView.initUI(SummaryView.java:115)
	at org.graalvm.visualvm.heapviewer.ui.SummaryView.getComponent(SummaryView.java:83)
	at org.graalvm.visualvm.heapviewer.truffle.ui.TruffleSummaryView.getComponent(TruffleSummaryView.java:148)
	at org.graalvm.visualvm.heapviewer.ui.HeapViewerComponent$MainView.selectFeature(HeapViewerComponent.java:366)
	at org.graalvm.visualvm.heapviewer.ui.HeapViewerComponent$MainView$2.fireItemStateChanged(HeapViewerComponent.java:498)
	at javax.swing.AbstractButton$Handler.itemStateChanged(AbstractButton.java:2355)
	at javax.swing.DefaultButtonModel.fireItemStateChanged(DefaultButtonModel.java:455)
	at javax.swing.JToggleButton$ToggleButtonModel.setSelected(JToggleButton.java:272)
	at javax.swing.ButtonGroup.setSelected(ButtonGroup.java:165)
	at javax.swing.JToggleButton$ToggleButtonModel.setSelected(JToggleButton.java:254)
	at javax.swing.AbstractButton.setSelected(AbstractButton.java:348)
	at org.graalvm.visualvm.lib.ui.swing.StayOpenPopupMenu.performAction(StayOpenPopupMenu.java:132)
	at org.graalvm.visualvm.lib.ui.swing.StayOpenPopupMenu.performAction(StayOpenPopupMenu.java:143)
	at org.graalvm.visualvm.lib.ui.swing.StayOpenPopupMenu.access$000(StayOpenPopupMenu.java:71)
	at org.graalvm.visualvm.lib.ui.swing.StayOpenPopupMenu$RadioButtonItem.processMouseEvent(StayOpenPopupMenu.java:257)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
[catch] at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: MacOS
 - JDK version 1.8.0_222; OpenJDK 64-Bit Server VM 25.222-b10; AdoptOpenJDK
 - Version 1.8

**Additional context**
n/a

CC @eregon.

**Comment by jisedlac** [comment] 2020-05-12 00:42
Can you please specify the GraalVM version from which the heap dump has been taken and VisualVM version you're using? Is the process a Ruby REPL (`GRAALVM_HOME/bin/ruby`)?

**Comment by chrisseaton** [comment] 2020-05-12 00:45
It's master of everything as of when the bug was posted. It's not a REPL.

**Comment by thurka** [comment] 2020-05-12 07:49
We need the heap dump to reproduce this issue. Ordinary heap dump from ruby process works fine. Can you prepare something for us?

**Comment by chrisseaton** [comment] 2020-05-12 15:09
Heap dump available from https://www.dropbox.com/s/2zrdzs73ebvvsn6/heapdump-1589295977489.hprof.gz.

Produced using TruffleRuby `43605b367e5f6e017928f350c9a35187c27cd161`, Graal `60de305c9a9c1c1b0f17265f9918b555a9b2e45f`, VisualVM `8fc6de2dcf31df19270716042a32b947d4d53682`, building TruffleRuby in the `jvm-ce` configuration.

I'm running https://github.com/chrisseaton/liquid/tree/cab `6a494bd48b278fd4f2a7369cfa5298719633f0dc`, with `bundle install` and then `bundle exec ruby performance/benchmark-cart-render.rb`. (@eregon will be able to help you reproduce from those instructions.)

**Comment by thurka** [comment] 2020-05-12 15:12
Thanks, I am able to reproduce it.

**Comment by thurka** [comment] 2020-05-12 16:06
It looks like there is a dynamic object whose property name is another dynamic object (????) instead of String or HiddenKey.
This strange dynamic object is value of `logicalClass` field of  `org.truffleruby.core.string.StringLayoutImpl$StringType#1`.
Does it make sense to you?

**Comment by thurka** [comment] 2020-05-12 16:11
<img width="1141" alt="ruby_npe" src="https://user-images.githubusercontent.com/22048069/81718244-cb3ecc00-947b-11ea-9e17-37b8f9a5e07b.png">
Strange dynamic object property (look for !!!!).

**Comment by eregon** [comment] 2020-05-12 16:19
DynamicObject can have anything as a key.
`Primitive.object_hidden_var_set` in TruffleRuby allows use an arbitrary key, I see it used with Ruby Symbol but not with Ruby String (which is what a `org.truffleruby.core.string.StringLayoutImpl$StringType` is).

**Comment by thurka** [comment] 2020-05-12 16:21
I don't think it a good idea to put something immutable as key. Moreover HiddenKey has only constructor with a String.

**Comment by chrisseaton** [comment] 2020-05-12 16:46
It's probably `Symbol` which may be technically mutable but logically is not.

We could have a new class `RubyHiddenKey` and then do something like `Primitive.object_hidden_var_set Primitive.hidden_key_from_symbol(:foo)`.

**Comment by eregon** [comment] 2020-05-12 17:05
It's actually `RB_TYPE` here: https://github.com/oracle/truffleruby/blob/43605b367e5f6e017928f350c9a35187c27cd161/lib/truffle/truffle/cext.rb#L19

We should use a HiddenKey or Symbol instead, to make it easier to debug, otherwise one needs to look at the references to that Object to find out the name of the constant.

@thurka told me Symbol as keys of DynamicObject should work fine.

**Comment by thurka** [comment] 2020-05-12 17:29
NPE should be fixed by [1ecd317](https://github.com/oracle/visualvm/commit/1ecd317c485b25da6eda6fe80da7f12db4d8f920).

**Closed by thurka** 2020-05-12 17:29 UTC
Labels: bug

**Comment by chrisseaton** [comment] 2020-05-13 14:16
Confirmed. Thanks.

**Comment by chrisseaton** [comment] 2020-05-14 00:17
Do you know how we can get this update into GraalVM? I'm not sure of the interaction between these two projects and how we can update the version? It just seems to download binaries but I don't recognise the version scheme?

**Comment by thurka** [comment] 2020-05-14 06:22
> Do you know how we can get this update into GraalVM? 
Yes, I know.

>I'm not sure of the interaction between these two projects and how we can update the >version? It just seems to download binaries but I don't recognise the version scheme?

I will tell you once it is part of GraalVM-dev.

**Comment by eregon** [comment] 2020-05-25 10:29
FYI I made the hidden variables in Truffle::CExt to be `HiddenKey` rather than just `Object.new` so they can be analyzed much more easily in VisualVM and other tooling: https://github.com/oracle/truffleruby/commit/345b9d560db8d316e8275be33df1928d1f65f1eb#diff-eacb9cb7d1ba5dcda075af1a1b64170d

**Comment by thurka** [comment] 2020-06-06 19:45
> Do you know how we can get this update into GraalVM? I'm not sure of the interaction between these two projects and how we can update the version? It just seems to download binaries but I don't recognise the version scheme?

FYI, fixed version of VisualVM is now part of GraalVM-dev. https://github.com/oracle/graal/commit/dedf0728dc88eaf4ddccda2d7b4398b14b812ec9

**Comment by chrisseaton** [comment] 2020-06-06 19:48
Thanks.

I wish that VisualVM was an `mx` component though, or could otherwise be included as a source dependency. If I want to update to a new VisualVM version internally I think I currently have to build and then host the binary somewhere? That's not ideal for me.
