### ISSUE TITLE
Metaspace not reported on jdks > 8

### ISSUE THREAD

**Issue by tstuefe** [oracle/visualvm#83] opened 2018-04-28 06:43 UTC
Hi, Metaspace does not get reported correctly on my machine (Ubuntu 16.04). The tab instead is named "PermGen" and shows nothing.

I tried with openjdk11 (current build) as well as oracle jdk 10.

Oracles old visualvm from jdk8 has the same problem.

If this can be fixed (with reasonable time effort) on the openjdk side, please give me a pointer, I am ojdk contributor.

**Comment by thurka** [comment] 2018-04-30 07:48
This is strange, because 'Metaspace' was added in VisualVM 1.3.6. What version of VisualVM you use? Can you attach VisualVM messages.log? What application do you monitor? What version of JDK does it use?

**Comment by tstuefe** [comment] 2018-05-03 06:31
I use visualvm 1.4.1 (downloaded from github). 

Where do I find the logfiles?

The app I monitor is just a repro case for metaspace consumption. I am openjdk developer and currently work on metaspace monitoring.

VisualVM runs with --jdkhome <oracle jdk 1.8.0_172>

Monitored VMs run with oracle jdk 1.8.0_172 (failure, "Permgen" + empty pane), openjdk 11 tip (same failure). If monitored VM runs with oracle jdk 1.8.0_172, Metaspace pane shows up correctly.

**Comment by tstuefe** [comment] 2018-05-03 06:38
Okay, found the button...

[visual-vm-logfile.txt](https://github.com/oracle/visualvm/files/1969822/visual-vm-logfile.txt)

Logfile was written after I started up VisualVM, selected monitoree, selected "Permgen" tab which was empty. Monitoree was oracle jdk 10.

**Comment by thurka** [comment] 2018-05-03 07:09
OK, I was able to reproduce it when monitoring application is running on JDK 10. JDK 9 works fine.
JDK 11 is not supported by VisualVM 1.4.1.

**Comment by tstuefe** [comment] 2018-05-03 09:04
As I said, I can reproduce the error with oracle jdk 10

**Comment by thurka** [comment] 2018-05-03 10:07
> As I said, I can reproduce the error with oracle jdk 10.
Can you, please, create the application snapshot of such application? Once you have it, attach it to this issue. Thanks.

**Comment by tstuefe** [comment] 2018-05-03 12:12
Sure, but what is an application snapshot? (I am new to visualvm)

**Comment by tstuefe** [comment] 2018-05-04 06:35
I'm sorry, I will not be able to follow up this week, too much on my plate.

But you wrote you were able to reproduce this with  JDK 10.0.2-ea. I am seeing this error with jdk 10.0.1. So, since you have a repro case, do you still need anything from me?

**Comment by thurka** [comment] 2018-05-04 08:46
> I am seeing this error with jdk 10.0.1. 

There you go. You were telling me that you were able to reproduce it with JDK 10 and now it is 10.0.1.

> So, since you have a repro case, do you still need anything from me?

If you can confirm that JDK 10 (not JDK 10.0.1 or JDK 10.0.2) works for you, I have a repro case and I know how to fix it.

**Comment by thurka** [comment] 2018-08-08 13:40
Probably duplicate of GH-86.

**Closed** 2018-08-08 13:40 UTC
