### ISSUE TITLE
JMX heap dump on kubernetes

### ISSUE THREAD

**Issue by mikebell90** [oracle/visualvm#188] opened 2020-04-13 20:54 UTC
**Describe the bug**
VisualVM (similar to #187 ) is not able to take a heap dump, because to access JMX in kubernetes, I must "port-forward"

**To Reproduce**
1. 
-Dcom.sun.management.jmxremote
-Dcom.sun.management.jmxremote.authenticate=false
-Dcom.sun.management.jmxremote.ssl=false
-Dcom.sun.management.jmxremote.local.only=false
-Dcom.sun.management.jmxremote.port=8081
-Dcom.sun.management.jmxremote.rmi.port=8081
-Djava.rmi.server.hostname=127.0.0.1

2. launch pod with the above, and a containerPort of 8081
3. kubectl port-forward (podname) 8081:8081
4. Hit visualvm, and add jmx connection 127.0.0.1:8081
5. Open it
6. Try to take a heap dump

The problem is VisualVM is trying to be smart (local viz remote). We need a way to disable it, Or mark an item Remote

**Comment by mikebell90** [comment] 2020-04-13 21:15
Workaround: If you install the mbeans plugin you can take a heap dump with the MXBean

**Comment by mikebell90** [comment] 2020-04-17 14:11
The fundamental issue to clarify is that port forwarding establishes a local proxy. Since it’s local visualvm doesn’t use the remote api for heaps. Clearly it works since if I go to the mbean directly I can modify it . Ask is probably a checkbox to force “remote mode”

**Comment by hoxu** [comment] 2020-05-06 10:10
The same problem happens with "Add Remote Host" (non-JMX) if you are using `kubectl port-forward` or similar manner of port forwarding.

> Host localhost already monitored as Local

A checkbox for forcing remote mode would indeed be nice.

**Comment by thurka** [comment] 2020-06-16 06:59
This is duplicate of GH-187.

**Closed by thurka** 2020-06-16 06:59 UTC
