### ISSUE TITLE
Memory pools plugin won't install

### ISSUE THREAD

**Issue by vrolijken** [oracle/visualvm#25] opened 2017-05-22 15:08 UTC
I see a memory pools plugin, which is hosted on java.net (which no longer exists). It won't install and that stops the installation of all plugins: 
Version: 1.0 
Author: Kirk Pepperdine 
Date: 31-12-12 
Source: VisualVM Plugins Center 
Homepage: http://java.net/projects/memorypoolview

**Comment by jisedlac** [comment] 2017-05-22 16:36
Java.net which hosted plugins for VisualVM 1.3.8 and earlier has been shut down, the plugins cannot be installed using the Tools | Plugins action any more.

Please get the most recent VisualVM at https://visualvm.github.io/download.html or download & install plugins for VisualVM 1.3.8 and earlier manually - https://visualvm.github.io/pluginscenters.html.

**Comment by jisedlac** [comment] 2017-05-22 16:39
I can see the problem now, the Memory Pools plugin for VisualVM 1.3.9 points to https://java.net/downloads/memorypoolview/com-kodewerk-visualvm-memorypoolsb4.nbm.

Needs to be fixed, reopening. Thanks for the report!

**Comment by ullenboom** [comment] 2017-06-05 19:16
Same problem with Visual GC:

Networking problem in https://github.com/visualvm/visualvm.src/releases/download/1.3.9/com-sun-tools-visualvm-modules-visualgc.nbm

**Comment by jisedlac** [comment] 2017-06-06 08:53
I don't see any problem with Visual GC - it installs correctly for VisualVM 1.3.9 on my side.

**Comment by ullenboom** [comment] 2017-06-07 05:55
Too strange, did the same thing again and now it works.

**Comment by thurka** [comment] 2017-06-15 07:08
@kcpeppe Kirk, where is the new home of Memory Pools plugin?

**Comment by phlbrz** [comment] 2017-06-23 19:43
Hello!

@jisedlac I don't know how to generate an .nbm but I have the jar and xml files and copied to ~/.visualvm/

The files: [1.3.9.tar.gz](https://github.com/oracle/visualvm/files/1098893/1.3.9.tar.gz)

And the files has to be at:
~/.visualvm/1.3.9/update_tracking/com-kodewerk-visualvm-memorypools.xml
~/.visualvm/1.3.9/config/Modules/com-kodewerk-visualvm-memorypools.xml
~/.visualvm/1.3.9/modules/com-kodewerk-visualvm-memorypools.jar

So just untar inside your user ~/.visualvm/

Thank's!

**Comment by yogeshkumararora** [comment] 2017-06-24 13:50
Hi,

Thanks for creating the tar file.

I tried this on Mac, but visualvm not picking the directory ~/.visualvm.

Thanks,
Yogesh

**Comment by phlbrz** [comment] 2017-06-24 14:30
I don't know on Mac. I did it on Debian. Sorry.
But you can look for your user folder if it has this directory and place there I think.

**Comment by kcpeppe** [comment] 2017-06-24 21:23
Hi,

I apologize for late response. I see the project is not yet been uploaded to the web after java.net disappeared. I’ll be uploading it to my GitHub account very shortly. My account is kcpeppe.

Kind regards,
Kirk

**Comment by provosGH** [comment] 2017-08-09 02:52
HI, kcpeppe:
is the the memorypools plugin uploaded to your GitHub?the kcpeppe/memorypoolview  project is emptry. it was uploaded to some project else?
Kind regards! @kcpeppe

**Comment by rickardrockard** [comment] 2017-09-12 12:51
Hi @kcpeppe, just like the others, I'm looking for your plugin but can only find the empty project on your GitHub. Also tried the method suggested by @phlbrz and copied the files to the corresponding folders on my Windows installation, but it didn't work. Hoping for a commit from you!

**Comment by vrolijken** [comment] 2017-09-19 08:20
I unpacked the tar from @phlbrz (thanks for that!) but unfortunately it's not working for me. There does not seem to be a pom file for @kcpeppe 's project, nor could I get it imported in NetBeans (that I downloaded and installed for this). I tried to create a new plugin module in NetBeans and import the source code in that, but that got me up to a level where it now says stuff like "Warning: no numbered cluster matching bare name 'H:\Home\visualvm\visualvm_139\apisupport' found". I'm quite lost now and have spend quite some time trying to fix this. Anybody got any solutions?

**Comment by rickardrockard** [comment] 2017-09-19 08:29
This issue isn't closed, it is https://github.com/oracle/visualvm/issues/41 that is closed since it is a duplicate of this issue. I'm not sure how to make the plugin work with NetBeans, but it sounds like it's not really what you want to do. It sounds like what you want to do is download the precompiled version 1.39 of VisualVM from https://visualvm.github.io/ and use that. Start it once, and you will have %APPDATA%\VisualVM\1.3.9 created. Close VisualVM, unpack the files from the tar file into the appdata file structure and start VisualVM which will now have the plugin installed.

**Comment by vrolijken** [comment] 2017-09-19 08:59
I did that to no avail. Found out what the problem was though: I started using the `--userdir` parameter. After I untarred the tar file *there* everything worked!

**Comment by thurka** [comment] 2017-11-21 13:23
Memory pools plugin was removed from VisualVM 1.3.9 plugins centre until com-kodewerk-visualvm-memorypoolsb4.nbm is available somewhere.

**Closed by thurka** 2017-11-21 13:23 UTC

**Comment by chs8788** [comment] 2019-05-30 05:45
thanks got working by copying the files

**Comment by manueljordan** [comment] 2020-07-28 22:55
Hello

Without be rude, some plans to make available this plugin for the VisualVM 2.0.x series?

Huge thanks in advance!
