### ISSUE TITLE
Missing modules may be published on Update Centers?Some plugins require plugin net.java.btrace.api to be installed.

### ISSUE THREAD

**Issue by puchanghua** [oracle/visualvm#191] opened 2020-04-27 01:49 UTC
![20200427094934 png](https://user-images.githubusercontent.com/26082705/80326826-9708c000-886c-11ea-9f10-4f5dd487bda6.png)

**Comment by thurka** [comment] 2020-04-27 07:37
Thanks for spotting this. The problem is now fixed.

**Closed by thurka** 2020-04-27 07:37 UTC
Labels: bug
