### ISSUE TITLE
Arguments line of remote JVM cropped at 1024 characters

### ISSUE THREAD

**Issue by ro-kr** [oracle/visualvm#420] opened 2022-07-13 10:49 UTC
For a remote JVM instance connected to via jstatd the JVM arguments line is cropped at a limit of 1024 characters. This is visible in the JVM arguments tab of the JVM window. It also affects a custom name of the JVM, if specified by JVM CLI option `visualvm.display.name`. VisualVM parses this option from the JVM arguments line. If the option appears (partly) beyond the 1024 characters limit then VisualVM displays a cropped name or completely ignores the custom name.

I guess this bug is caused by #291 and affects all versions since 2.1.0.

**Comment by thurka** [comment] 2022-07-18 13:35
I don't think this is caused by #291. Can you please provide more information? Steps to reproduce would be great. Note that for remote connection, JMX must be also available, otherwise there is a default limit of 1024 characters imposed by jvmstat. You can change it by adding `-XX:PerfMaxStringConstLength=new_limit` to command line of the monitored application.

**Comment by thurka** [comment] 2022-08-08 08:57
@ro-kr Any update?

**Comment by ro-kr** [comment] 2022-08-08 15:14
@thurka Sorry for the late answer, I somehow overlooked your response.
Adding `-XX:PerfMaxStringConstLength=...` does the job.
Thanks for the hint.

**Comment by ro-kr** [comment] 2022-08-08 18:41
I thought that the issue was caused by #291 because if attaching to the JVM fails (that is, `getAttach()` returns null since the JVM is not local) then `jmxSupport.getJvmArgs()` is not called because `args` is not null:
#### JVMImpl.java
```java
private String getJvmArgsJvmstat() {
    String args = jvmstatModel.getJvmArgs();
    if (args.length() == 1024) {
        AttachModel attach = getAttach();
        if (attach != null) {
            args = attach.getJvmArgs();
        }
        if (args == null) {
            args = jmxSupport.getJvmArgs();
        }
        ...
```
I think `args` should be reset to null before the call to `getAttach()`.

**Comment by ro-kr** [comment] 2022-08-08 19:22
Great, thanks!

**Comment by thurka** [comment] 2022-08-11 12:29
Fixed in master.

**Closed by thurka** 2022-08-11 12:29 UTC
