### ISSUE TITLE
HprofHeap ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by kcpeppe** [oracle/visualvm#29] opened 2017-06-14 18:21 UTC
Ultimately the setup on a new machine was to debug this problem. This heap dump is viewable in MAT and in YourKit but VisualVM throws this exception. MAT does report overlapping array addresses but it ignores the problem and continues to complete the loading process. I was hoping to debug this problem but it drops into source code that isn't readily available.

SEVERE [org.openide.util.RequestProcessor]: Error in RequestProcessor com.sun.tools.visualvm.heapdump.impl.HeapDumpView$MasterViewSupport$1
java.lang.ArrayIndexOutOfBoundsException: -70
	at org.netbeans.lib.profiler.heap.HprofHeap.fillTagBounds(HprofHeap.java:1051)
	at org.netbeans.lib.profiler.heap.HprofHeap.<init>(HprofHeap.java:133)
	at org.netbeans.lib.profiler.heap.HeapFactory.createHeap(HeapFactory.java:87)
	at org.netbeans.lib.profiler.heap.HeapFactory.createHeap(HeapFactory.java:69)
	at org.netbeans.modules.profiler.heapwalk.HeapWalker.createHeap(HeapWalker.java:193)
	at org.netbeans.modules.profiler.heapwalk.HeapWalker.<init>(HeapWalker.java:92)
	at com.sun.tools.visualvm.heapdump.impl.HeapDumpView$MasterViewSupport$1.run(HeapDumpView.java:136)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
Caused: org.openide.util.RequestProcessor$SlowItem: task failed due to
	at org.openide.util.RequestProcessor.post(RequestProcessor.java:419)
	at com.sun.tools.visualvm.heapdump.impl.HeapDumpView$MasterViewSupport.loadHeap(HeapDumpView.java:133)
	at com.sun.tools.visualvm.heapdump.impl.HeapDumpView$MasterViewSupport.<init>(HeapDumpView.java:110)
	at com.sun.tools.visualvm.heapdump.impl.HeapDumpView.createComponent(HeapDumpView.java:70)
	at com.sun.tools.visualvm.core.ui.DataSourceView.getView(DataSourceView.java:184)
	at com.sun.tools.visualvm.core.ui.DataSourceWindowTabbedPane$ViewContainer.<init>(DataSourceWindowTabbedPane.java:189)
	at com.sun.tools.visualvm.core.ui.DataSourceWindow.addView(DataSourceWindow.java:75)
	at com.sun.tools.visualvm.core.ui.DataSourceWindowManager$8.run(DataSourceWindowManager.java:294)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:302)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
[catch] at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by thurka** [comment] 2017-06-15 06:56
What do you mean by `it drops into source code that isn't readily available` ? As you can see from the package `org.netbeans.lib.profiler.heap`,  this code is from NetBeans. So the best way to debug this is to debug it NetBeans dev. build. I guess you already know how to debug NetBeans, am I right? BTW: Can you share the heap dump? It looks like it is somehow broken.

**Comment by kcpeppe** [comment] 2017-06-15 08:13
Sorry to say I can't share the heap dump. I've not debugged NetBeans but I think I'm going to have to sort that one out.

**Comment by thurka** [comment] 2017-06-15 09:42
FYI: `org.netbeans.lib.profiler.heap` package is in `lib.profiler` module.

**Comment by thurka** [comment] 2017-11-21 13:37
Closing the issue until we are able to reproduce ArrayIndexOutOfBoundsException.

**Closed by thurka** 2017-11-21 13:37 UTC

**Comment by PuszekSE** [comment] 2018-07-05 11:40
@thurka @kcpeppe 
I've actually found that same exact issue within one of production server's heap dumps.

> -------------------------------------------------------------------------------
> >Log Session: Thursday, July 5, 2018 1:05:10 PM CEST
> [...]
> INFO [org.netbeans.modules.autoupdate.updateprovider.DownloadListener]: Reading URL https://visualvm.java.net/uc/8u40/updates.xml.gz?unique=0bd161e76-cd08-420e-886c-0b90d07b593d_60aeb6a7-8f78-4aa6-a510-cf3a82ec828c failed (java.io.IOException: Server returned HTTP response code: 503 for URL: http://www.oracle.com/splash/java.net/maintenance/index.html)
> INFO [org.netbeans.modules.autoupdate.ui.actions.AutoupdateCheckScheduler]
> java.io.IOException: Server returned HTTP response code: 503 for URL: http://www.oracle.com/splash/java.net/maintenance/index.html
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
> 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
> 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1433)
> 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1431)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1430)
> 	at org.netbeans.modules.autoupdate.updateprovider.NetworkAccess$Task$2.call(NetworkAccess.java:154)
> 	at org.netbeans.modules.autoupdate.updateprovider.NetworkAccess$Task$2.call(NetworkAccess.java:122)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused: java.io.IOException: Server returned HTTP response code: 503 for URL: http://www.oracle.com/splash/java.net/maintenance/index.html
> 	at org.netbeans.modules.autoupdate.updateprovider.DownloadListener.notifyException(DownloadListener.java:64)
> 	at org.netbeans.modules.autoupdate.updateprovider.AutoupdateCatalogCache.copy(AutoupdateCatalogCache.java:207)
> 	at org.netbeans.modules.autoupdate.updateprovider.AutoupdateCatalogCache.writeCatalogToCache(AutoupdateCatalogCache.java:60)
> 	at org.netbeans.modules.autoupdate.updateprovider.AutoupdateCatalogProvider.refresh(AutoupdateCatalogProvider.java:115)
> 	at org.netbeans.modules.autoupdate.services.UpdateUnitProviderImpl.refresh(UpdateUnitProviderImpl.java:141)
> 	at org.netbeans.api.autoupdate.UpdateUnitProvider.refresh(UpdateUnitProvider.java:157)
> [catch] at org.netbeans.modules.autoupdate.ui.actions.AutoupdateCheckScheduler$4.run(AutoupdateCheckScheduler.java:116)
> 	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1384)
> 	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:1994)
> WARNING [org.netbeans.TopSecurityManager]: use of system property netbeans.home has been obsoleted in favor of InstalledFileLocator/Places at org.netbeans.Clusters.relativeDirsWithHome(Clusters.java:104)
> SEVERE [org.openide.util.RequestProcessor]: Error in RequestProcessor com.sun.tools.visualvm.heapdump.impl.HeapDumpView$MasterViewSupport$1
> java.lang.ArrayIndexOutOfBoundsException: -11
> 	at org.netbeans.lib.profiler.heap.HprofHeap.fillTagBounds(HprofHeap.java:1013)
> 	at org.netbeans.lib.profiler.heap.HprofHeap.<init>(HprofHeap.java:95)
> 	at org.netbeans.lib.profiler.heap.HeapFactory.createHeap(HeapFactory.java:49)
> 	at org.netbeans.lib.profiler.heap.HeapFactory.createHeap(HeapFactory.java:31)
> 	at org.netbeans.modules.profiler.heapwalk.HeapWalker.createHeap(HeapWalker.java:155)
> 	at org.netbeans.modules.profiler.heapwalk.HeapWalker.<init>(HeapWalker.java:54)
> 	at com.sun.tools.visualvm.heapdump.impl.HeapDumpView$MasterViewSupport$1.run(HeapDumpView.java:116)
> 	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1384)
> [catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:1994)
> java.lang.ArrayIndexOutOfBoundsException
> SEVERE [org.openide.util.RequestProcessor]: Error in RequestProcessor com.sun.tools.visualvm.heapdump.impl.HeapDumpView$MasterViewSupport$1
> java.lang.ArrayIndexOutOfBoundsException
> SEVERE [org.openide.util.RequestProcessor]: Error in RequestProcessor com.sun.tools.visualvm.heapdump.impl.HeapDumpView$MasterViewSupport$1
> java.lang.ArrayIndexOutOfBoundsException
> SEVERE [org.openide.util.RequestProcessor]: Error in RequestProcessor com.sun.tools.visualvm.heapdump.impl.HeapDumpView$MasterViewSupport$1
> java.lang.ArrayIndexOutOfBoundsException
> INFO [org.netbeans.core.windows.persistence]: [PersistenceManager.getTopComponentForID] Problem when deserializing TopComponent for tcID:'com#002Esun#002Etools72625A45#002EDataSourceWindow_2'. Reason: Top component com#002Esun#002Etools72625A45#002EDataSourceWindow_2 could not be located or loaded from Components folder.
com.sun.tools.visualvm.heapdump.impl.HeapDumpView$MasterViewSupport$1
> java.lang.ArrayIndexOutOfBoundsException
> SEVERE [org.openide.util.RequestProcessor]: Error in RequestProcessor com.sun.tools.visualvm.heapdump.impl.HeapDumpView$MasterViewSupport$1
> java.lang.ArrayIndexOutOfBoundsException
