### ISSUE TITLE
Can't open core dump

### ISSUE THREAD

**Issue by zeroeightysix** [oracle/visualvm#172] opened 2020-01-22 17:38 UTC
**Problem**
I'm attempting to load a core dump into VisualVM. It fails with VisualVM telling me it is not a valid core dump.

I can reproduce every time by:
* Allow the JVM to crash
* Start up VisualVM and double click "VM Coredumps"
* Provide the core dump generated when the JVM crashed
* Press OK - this will fail because '*filename* is not a valid core dump!'

I'm quite sure the file I am providing is a valid core dump because:
* It was generated by `coredumpctl dump --output core.pid` after a JVM crash.
  * My `kernel.core_pattern` variable:
    ```
    $ sysctl kernel.core_pattern
    kernel.core_pattern = |/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h
    ```
* I can open and explore the core dump using GDB
* `ulimit -c` is `unlimited`

**Environment**
*OS*: Arch linux
*JDK*: OpenJDK 11:
```
$ java --version
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10)
OpenJDK 64-Bit Server VM (build 11.0.6+10, mixed mode)
```
*VisualVM*: Built and ran on OpenJDK 8, as of commit 529a6d557bbf97d266020718dbe182049efbd458
![image](https://user-images.githubusercontent.com/27009727/72918369-d394bf00-3d45-11ea-864e-db7a9ade4986.png)
(Please note that for opening the core dump, OpenJDK 11 was selected as java home)

**Exceptions**
When selecting the core dump, and selecting OpenJDK 11 as java home, no exceptions arise.
When selecting the core dump, and selecting OpenJDK 8 as java home (not the java version the dump was generated by), [this](https://gist.githubusercontent.com/zeroeightysix/fe618850e1866ed358d85a36b90d375c/raw/729649cc0fc1773eb10c9de5e15ba137fe31c335/gistfile1.txt) exception arises

**Comment by thurka** [comment] 2020-01-31 09:59
Can you, please attach `messages.log` file. Thanks.

**Comment by zeroeightysix** [comment] 2020-01-31 14:53
> Can you, please attach `messages.log` file. Thanks.

[Here](https://gist.githubusercontent.com/zeroeightysix/fe00c916455bf0a3e56f84690a29aa21/raw/d928d51d1a4f174390e1dc0ef556c6843b906cf4/messages.log)'s the messages.log file when I select the correct JDK (11) when opening the coredump.

**Comment by thurka** [comment] 2020-01-31 18:42
Thanks, can you please try to run VisualVM on the same JDK 11 as was used in core dump?

**Comment by zeroeightysix** [comment] 2020-02-01 18:37
Sure. [Here](https://gist.githubusercontent.com/zeroeightysix/4e44fe83004adc0e2d2fa0bd100bbedd/raw/3da968810619cfe984fe9494dd58cead235805d9/messages.log)'s the log.

**Comment by thurka** [comment] 2020-02-02 09:38
Thanks for the log file. I am able to reproduce the issue.

**Comment by thurka** [comment] 2020-02-02 21:07
Can you please try the following workaround:

1. Create empty file `/usr/lib/jvm/java-11-openjdk/lib/sa-jdi.jar`
2. Run visualvm using the following to the commandline: `/usr/share/visualvm/bin/visualvm --jdkhome /usr/lib/jvm/java-11-openjdk -J--add-modules=jdk.hotspot.agent -J--add-exports=jdk.hotspot.agent/sun.jvm.hotspot=ALL-UNNAMED -J--add-exports=jdk.hotspot.agent/sun.jvm.hotspot.runtime=ALL-UNNAMED -J--add-exports=jdk.hotspot.agent/sun.jvm.hotspot.memory=ALL-UNNAMED -J--add-exports=jdk.hotspot.agent/sun.jvm.hotspot.oops=ALL-UNNAMED -J--add-exports=jdk.hotspot.agent/sun.jvm.hotspot.utilities=ALL-UNNAMED`

**Comment by zeroeightysix** [comment] 2020-02-02 21:14
I tried the workaround. Unfortunately, the issue persists. [Here](https://gist.githubusercontent.com/zeroeightysix/2ff900c08573e7026cc2dc351521c7fc/raw/ae8f7410e05ec0ccba95489dbe8a117f9468ec73/messages.log) is the log file.

**Comment by thurka** [comment] 2020-02-03 08:52
Ok, let us see if JDK itself can read the core dump. Please run:
`/usr/lib/jvm/java-11-openjdk/bin/jhsdb jinfo --exe /usr/lib/jvm/java-11-openjdk/bin/java --core <your_core_dump_file>`
and post the output.

**Comment by zeroeightysix** [comment] 2020-02-03 17:21
Looks like it can't:
```
$ /usr/lib/jvm/java-11-openjdk/bin/jhsdb jinfo --exe /usr/lib/jvm/java-11-openjdk/bin/java --core IdeaProjects/imgui/core.43549
Attaching to core IdeaProjects/imgui/core.43549 from executable /usr/lib/jvm/java-11-openjdk/bin/java, please wait...
Error attaching to core file: Can't attach to the core file
sun.jvm.hotspot.debugger.DebuggerException: Can't attach to the core file
	at jdk.hotspot.agent/sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal.attach0(Native Method)
	at jdk.hotspot.agent/sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal.attach(LinuxDebuggerLocal.java:282)
	at jdk.hotspot.agent/sun.jvm.hotspot.HotSpotAgent.attachDebugger(HotSpotAgent.java:674)
	at jdk.hotspot.agent/sun.jvm.hotspot.HotSpotAgent.setupDebuggerLinux(HotSpotAgent.java:612)
	at jdk.hotspot.agent/sun.jvm.hotspot.HotSpotAgent.setupDebugger(HotSpotAgent.java:338)
	at jdk.hotspot.agent/sun.jvm.hotspot.HotSpotAgent.go(HotSpotAgent.java:305)
	at jdk.hotspot.agent/sun.jvm.hotspot.HotSpotAgent.attach(HotSpotAgent.java:157)
	at jdk.hotspot.agent/sun.jvm.hotspot.tools.Tool.start(Tool.java:191)
	at jdk.hotspot.agent/sun.jvm.hotspot.tools.Tool.execute(Tool.java:118)
	at jdk.hotspot.agent/sun.jvm.hotspot.tools.JInfo.runWithArgs(JInfo.java:139)
	at jdk.hotspot.agent/sun.jvm.hotspot.tools.JInfo.main(JInfo.java:144)
	at jdk.hotspot.agent/sun.jvm.hotspot.SALauncher.runJINFO(SALauncher.java:412)
	at jdk.hotspot.agent/sun.jvm.hotspot.SALauncher.main(SALauncher.java:543)
```
In case context matters, the core dump was generated while debugging a project in IntelliJ. [Here's](https://github.com/kotlin-graphics/imgui) a link to the project. It has quite a lot of native bindings.

**Comment by thurka** [comment] 2020-02-03 19:06
Thanks again for testing. The exception shows that the problem is in JDK and not in VisualVM - VisualVM uses same API as `bin/jhsdb` to access core dump. I am not sure that this is a problem with native methods. To rule it out - just create and open core dump from something else running on your JDK 11 - like `/usr/lib/jvm/java-11-openjdk/bin/jrunscript`. It looks to me that you could face https://bugs.openjdk.java.net/browse/JDK-8235637 . Can you try different JDK 11? JDK 11.0.4 should not be affected by JDK-8235637.

**Comment by thurka** [comment] 2020-02-07 12:53
It should be fixed by [above](https://github.com/oracle/visualvm/commit/64f2be474c76dd90302085aaaeef655f35ce305f) commit.

**Closed by thurka** 2020-02-07 12:53 UTC
Labels: bug
